name: Build MegaDumper EXE

on:
  workflow_dispatch: # Allows you to click a button to start the build manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

# Setup the MSBuild environment (Visual Studio compiler tools)
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Compile the .sln file into a Release executable
    - name: Compile Solution to EXE
      run: msbuild MegaDumper.sln /p:Configuration=Release /p:Platform="Any CPU"

    # Upload the compiled binary so you can download it
    - name: Upload Finished Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MegaDumper-Compiled
        path: "**/bin/Release/"
